### ISSUE TITLE
Error: Failed to capture cloned options

### ISSUE THREAD

**Issue by seantw** [overlookmotel/terser-sync#77]
terser-sync v0.1.1 with terser v5.26.0 work fine.

But terser versions >5.26.0 , the following error will occur:

`Error: Failed to capture cloned options at Object.minifySync (\node_modules\terser-sync\lib\index.js:106:10)`

**Comment by overlookmotel** [comment]
Since I originally published this, Terser added a `minify_sync` method.

So there is no longer any need for this package. I'd recommend just using Terser itself.
